#!/bin/sh

#include global config
. /etc/scripts/global.sh

PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
PPP_NUM=`echo $PPP_IFACE | sed 's/[^0-65535]//g'`

# disable forward
echo 0 > "/proc/sys/net/ipv4/conf/$PPP_IFACE/forwarding"
if [ "$radvdEnabled" = "1" ] && [ -f "/proc/sys/net/ipv6/conf/$PPP_IFACE/forwarding" ]; then
    echo 0 > "/proc/sys/net/ipv6/conf/$PPP_IFACE/forwarding"
fi

# del rules
iptables -D l2tpsrvfwd -i $PPP_IFACE -j ACCEPT > /dev/null 2>&1
iptables -D l2tpsrvfwd -o $PPP_IFACE -j ACCEPT > /dev/null 2>&1
iptables -D POSTROUTING -t nat ! -o $PPP_IFACE -j MASQUERADE > /dev/null 2>&1

# udpxy
iptables -D servicelimit -i $PPP_IFACE -m state --state NEW -p tcp --dport $UDPXYPort -j ACCEPT > /dev/null 2>&1

# SSH
iptables -D servicelimit -i $PPP_IFACE -m state --state NEW -p tcp --dport $RemoteSSHPort -j ACCEPT > /dev/null 2>&1

# FTP
iptables -D servicelimit -i $PPP_IFACE -m state --state NEW -p tcp --dport $FtpPort -j ACCEPT > /dev/null 2>&1

# DNS
iptables -D servicelimit -i $PPP_IFACE -m state --state NEW -p udp --dport 53 -j ACCEPT > /dev/null 2>&1

export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM
