#!/bin/sh

# if app not exist
if [ ! -f /bin/radvd ] || [ ! -d /proc/sys/net/ipv6 ]; then
    exit 0
fi

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t ipv6"

calculate_and_set_mtu() {
    # get mtu from wan
    wanmtu=`ip link show $real_wan_if | grep mtu | awk {' print $5 '}`
    # calculate mtu
    let "sitmtu=$wanmtu - 20"
    let "ipvmtu=$sitmtu - 40"

    # set mtu for lan
    sysctl -wq  net.ipv6.conf."$lan_if".mtu="$ipvmtu"
    if [ "$Lan2Enabled" = "1" ]; then
	sysctl -wq  net.ipv6.conf."$lan2_if".mtu="$ipvmtu"
    fi
}

start() {
    eval `nvram_buf_get 2860 radvdEnabled`
    if [ "$radvdEnabled" = "1" ]; then
	# check wan ip set
	if [ "$real_wan_ipaddr" = "" ]; then
	    $LOG "No ipv4 adress on wan, exit..."
	    exit 1
	fi

	# rebuild ipv6 rules
        service iptables restartv6

        # calculate and set mtu
        calculate_and_set_mtu

        $LOG "Tunel ipv6 in ipv4 configure and up"
        if [ "$ipv6_mode" = "6RD" ]; then
	    # this section for 6RD tunnel mode
	    relay6to4="192.88.99.127"										# The 6rd IPv4-gateway
	    ipv6subnet="$(echo -n `printf '%02X:' ${real_wan_ipaddr//./ } | awk -F: '{print($1$2":"$3$4)}'`)"	# Calculate subnet from real ipv4 adress
    	    ipv6prefix="2a02:2560"										# Your ISP's IPv6-prefix
	    $LOG "Tune and up 6rd interface"
	    ip -6 addr add ${ipv6prefix}:${ipv6subnet}::abca/128 dev $real_wan_if
	    ip tunnel add $tunif mode sit local $real_wan_ipaddr ttl 64
	    ip tunnel 6rd dev $tunif 6rd-prefix ${ipv6prefix}::/32
	    ip -6 addr add ${ipv6prefix}:${ipv6subnet}::abca/32 dev $tunif
	    ip link set $tunif up
	    $LOG "Replace ipv6 dgw to ::${relay6to4} dev $tunif"
	    ip -6 route replace ::/0 via ::${relay6to4} dev $tunif metric 1
	    $LOG "Set mtu $sitmtu to $tunif"
	    sysctl -wq net.ipv6.conf.$tunif.mtu="$sitmtu"
	    ip link set mtu $sitmtu dev $tunif
        elif [ "$ipv6_mode" = "6TO4" ]; then
	    # this section for 6to4 tunnel mode
	    relay6to4="192.88.99.1"										# The 6to4 IPv4-gateway
	    ipv6subnet="2000"											# Default 6to4 subnet
    	    ipv6prefix=`echo $real_wan_ipaddr | awk -F. '{ printf "2002:%02x%02x:%02x%02x", $1, $2, $3, $4 }'`	# Calculate prefix
	    $LOG "Up $tunif interface"
	    ip -6 link set $tunif up
	    $LOG "Set mtu $sitmtu to $tunif"
	    sysctl -wq net.ipv6.conf.$tunif.mtu="$sitmtu"
	    ip link set mtu $sitmtu dev $tunif
	    $LOG "Add adress ${ipv6prefix}::1/16 to $tunif"
	    ip -6 addr add ${ipv6prefix}::1/16 dev $tunif
	    $LOG "Add route to ${ipv6subnet}::/3 via ::${relay6to4} dev $tunif"
	    ip -6 route replace ${ipv6subnet}::/3 via ::${relay6to4} dev $tunif metric 1
        elif [ "$ipv6_mode" = "NATIVE" ]; then
	    # this section for native/dualstack mode
	    :
	fi

	# set defaults
        sysctl -w net.ipv6.conf.all.forwarding=1
	sysctl -w net.ipv6.conf.all.accept_ra=1
	sysctl -w net.ipv6.conf.all.accept_ra_pinfo=1
	sysctl -w net.ipv6.conf.all.autoconf=1

	if [ "$ipv6_mode" = "NATIVE" ]; then
	    $LOG "Always accept router advertisements for autoconfigure from wan $real_wan_if."
	    sysctl -w net.ipv6.conf.$real_wan_if.accept_ra=2
	else
	    $LOG "Set ${ipv6prefix}:${ipv6subnet}::1/64 to $lan_if"
	    ip -6 addr del ${ipv6prefix}:${ipv6subnet}::1/64 dev $lan_if	> /dev/null 2>&1
	    ip -6 addr add ${ipv6prefix}:${ipv6subnet}::1/64 dev $lan_if
	fi

	$LOG "Enable ipv6 forward"
	$LOG "Configure radvd"
        printf "
        interface $lan_if
            {
                AdvSendAdvert on;
                MinRtrAdvInterval 3;
                MaxRtrAdvInterval 10;
                AdvDefaultPreference high;
                prefix ${ipv6prefix}:${ipv6subnet}::1/64
                {
                        AdvOnLink off;
                        AdvAutonomous on;
                        AdvRouterAddr on;
                        AdvPreferredLifetime 20;
                        AdvValidLifetime 30;
                };
                RDNSS 2001:4860:4860::8888 2001:4860:4860::8844
                {
                        AdvRDNSSLifetime 10;
                };
            };
        " > /etc/radvd.conf

	$LOG "Starting radvd"
	radvd -C /etc/radvd.conf --debug=0 --logmethod=syslog &
    fi
}

stop() {
    if [ -f /var/run/radvd.pid ]; then
	$LOG  "Stop radvd daemon."

        # disable ra for all ifaces
	sysctl -w net.ipv6.conf.all.accept_ra=0
        sysctl -w net.ipv6.conf.all.forwarding=0

	# rebuild ipv6 rules
	service iptables stopv6

	killall -q radvd
	killall -q -SIGKILL radvd

	ip -6 route flush dev 6rd		> /dev/null 2>&1
	ip -6 addr flush dev 6rd		> /dev/null 2>&1
	ip -6 route flush dev sit0		> /dev/null 2>&1
	ip -6 addr flush dev sit0		> /dev/null 2>&1
	ip -6 route flush dev $real_wan_if	> /dev/null 2>&1
	ip -6 addr flush dev $real_wan_if	> /dev/null 2>&1
	#ip -6 route flush dev $lan_if		> /dev/null 2>&1
	#ip -6 addr flush dev $lan_if		> /dev/null 2>&1
	ip link set dev 6rd down		> /dev/null 2>&1
	ip link set dev sit0 down		> /dev/null 2>&1
	ip tunnel del 6rd			> /dev/null 2>&1
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
