#!/bin/sh

# if app not exist
if [ ! -f /bin/minidlnad ] || [ ! -d /proc/bus/usb ]; then
    exit 0
fi

#include global config
. /etc/scripts/global.sh

# include wait to web full load
. /etc/scripts/start_wait.sh

LOG="logger -t minidlnad"

SCAN_OPT=""

start() {
    get_param
    if [ "$DlnaEnabled" = "1" ]; then
     ( # send to background

	# wait to web full load
	start_wait

	# if need kill minidlnad
	pid=`pidof minidlnad`
	if [ "$pid" != "" ]; then
	    $LOG "Stop minidlnad."
	    killall -q minidlnad
	    sleep 2
	    #kill if not stopped
	    killall -q -SIGKILL minidlnad
        fi

	gen_config

	$LOG "Start minidlnad."
	if [ "$public" = "" ]; then
	    $LOG "Disc not mounted... minidlna cant start!"
	    exit 0
	fi

	/bin/minidlnad $SCAN_OPT
      ) & # send to background
    fi
}

stop() {
	# if need kill minidlnad
	pid=`pidof minidlnad`
	if [ "$pid" != "" ]; then
	    $LOG "Stop minidlnad."
	    killall -q minidlnad
	    sleep 2
	    #kill if not stopped
	    killall -q -SIGKILL minidlnad
        fi
}

get_param() {
    eval `nvram_buf_get 2860 DlnaEnabled dlnaPort dlnaDBPath dlna0Path dlna1Path dlna2Path`

    #include profile variables
    . /etc/profile
}

gen_config() {
    fname="/etc/minidlna.conf"

    # drop current
    rm -f $fname
    touch $fname

    # port for HTTP (descriptions, SOAP, media transfer) traffic
    echo "port=$dlnaPort" >> $fname
    # network interfaces to serve, comma delimited
    echo "network_interface=$lan_if" >> $fname
    #  scan fie path
    if [ "$dlna0Path" != "" ]; then
        echo "media_dir=$dlna0Path" >> $fname
    fi
    if [ "$dlna1Path" != "" ]; then
        echo "media_dir=$dlna1Path" >> $fname
    fi
    if [ "$dlna2Path" != "" ]; then
        echo "media_dir=$dlna2Path" >> $fname
    fi
    # set this if you would like to specify the directory where you want MiniDLNA to store its database and album art cache
    echo "db_dir=$dlnaDBPath" >> $fname
    echo "log_dir=$dlnaDBPath" >> $fname
    # set this if you want to customize the name that shows up on your clients
    echo "friendly_name=miniDLNA Server" >> $fname
    # other
    echo "album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg" >> $fname
    echo "inotify=yes" >> $fname
    echo "enable_tivo=no" >> $fname
    echo "strict_dlna=no" >> $fname
    echo "notify_interval=15" >> $fname
    echo "serial=12345678" >> $fname
    echo "model_number=1" >> $fname
    echo "max_connections=10" >> $fname
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

	rescan)
            SCAN_OPT="-r"
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart|rescan}"
            exit 1
esac
