NVDIR = $(ROOTDIR)/lib/libnvram
CFLAGS += -I$(NVDIR)
CFLAGS += -I$(ROOTDIR)/linux/include
LDFLAGS += -lnvram
EXEC = ated
SRCS = ated.c

#EXTRA_CFLAGS += -DDBG

all: $(EXEC)

$(EXEC): $(SRCS) $(ROOTDIR)/$(LINUXDIR)/include/linux/config.h
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ $@.c $(LDLIBS)

romfs:
	$(ROMFSINST) -S /bin/$(EXEC)

clean:
	-rm -f $(EXEC) *.o
