/* MiniDLNA Project
 * http://sourceforge.net/projects/minidlna/
 * (c) 2008-2009 Justin Maggard
 * generated by ./genconfig.sh on Птн Фев 28 13:31:26 EET 2014 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define OS_NAME			"Linux"
#define OS_VERSION		"Linux/Cross_compiled"
#define OS_URL			"http://www.kernel.org/"

/* full path of the file database */
#define DEFAULT_DB_PATH		"/media/sda1/minidlna"

/* full path of the log directory */
#define DEFAULT_LOG_PATH	"/media/sda1/minidlna"

#define USE_DAEMON 1

#define HAVE_LINUX_SENDFILE_API 1

/* Enable if inotify*/
#define HAVE_INOTIFY 1

/* Compile in TiVo support. */
#define TIVO_SUPPORT 1
/* Enable PnPX support. */
#define PNPX 0

#define HAVE_ICONV_H
#define HAVE_ICONV

#endif
