/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Library Configuration
 */

/*
 * Force build (Normally built when required)
 */
#undef  CONFIG_LIB_LIBGMP_FORCE
#define CONFIG_LIB_LIBPTHREAD_FORCE 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#define CONFIG_LIB_LIBNTFS3G_FORCE 1
#define CONFIG_LIB_ZLIB_FORCE 1
#undef  CONFIG_LIB_LIBSTDC_PLUS_FORCE
#define CONFIG_LIB_USB 1
#define CONFIG_LIB_NAT 1
#define CONFIG_LIB_FLEX 1
#define CONFIG_LIB_EVENT 1
#define CONFIG_LIB_CURL 1
#define CONFIG_LIB_PCAP 1
#define CONFIG_LIB_ICONV 1
#undef  CONFIG_LIB_NET
#undef  CONFIG_LIB_NL
#undef  CONFIG_LIB_NFNETLINK
#undef  CONFIG_LIB_UPNP

/*
 * Force build extra libraries in uClibc
 */
#define CONFIG_LIB_CRYPT_FORCE 1
#define CONFIG_LIB_LIBM_FORCE 1
#define CONFIG_LIB_NSL_FORCE 1
#define CONFIG_LIB_UTIL_FORCE 1
#define CONFIG_LIB_RESOLV_FORCE 1

/*
 * Network Applications
 */
#define CONFIG_USER_GOAHEAD_HTTPD 1
#undef  CONFIG_USER_GOAHEAD_IPV6
#undef  CONFIG_USER_GOAHEAD_SSL
#define CONFIG_USER_GOAHEAD_HOSTNAME 1
#define CONFIG_USER_GOAHEAD_HAS_WPSBTN 1
#define CONFIG_USER_GOAHEAD_LANG_EN 1
#undef  CONFIG_USER_GOAHEAD_LANG_ZHTW
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#undef  CONFIG_USER_MATRIXSSL
#define CONFIG_USER_DNSMASQ 1
#undef  CONFIG_USER_SAMBA
#define CONFIG_USER_SAMBA3 1
#define CONFIG_LIB_ICONV 1
#define CONFIG_USER_TRANSMISSION 1
#define CONFIG_LIB_EVENT 1
#define CONFIG_LIB_CURL 1
#define CONFIG_LIB_ZLIB_FORCE 1
#define CONFIG_USER_OPENSSL 1
#define CONFIG_USER_STORAGE 1
#define CONFIG_USER_IGMP_PROXY 1
#define CONFIG_USER_UDPXY 1
#define CONFIG_USER_WIVE 1
#undef  CONFIG_USER_KABINET
#define CONFIG_USER_INADYN 1
#define CONFIG_USER_IPTABLES_IPTABLES 1
#undef  CONFIG_USER_IPTABLES_SAVE_RESTORE
#define CONFIG_USER_IPTABLES_IP6TABLES 1
#define CONFIG_USER_DROPBEAR 1
#define CONFIG_USER_P910ND 1
#define CONFIG_USER_PPPD 1
#define CONFIG_USER_PPPD_CHAT 1
#define CONFIG_USER_XL2TPD 1
#define CONFIG_USER_PARPROUTED 1
#undef  CONFIG_USER_ZEBRA
#undef  CONFIG_USER_SNMPD
#define CONFIG_USER_MINIUPNPD 1
#define CONFIG_USER_XUPNPD 1
#define CONFIG_USER_RADVD 1
#define CONFIG_USER_DHCP6 1
#define CONFIG_USER_DHCP6_SERVER 1
#define CONFIG_USER_DHCP6_CLIENT 1
#define CONFIG_USER_CDP 1
#define CONFIG_USER_LLTD 1
#undef  CONFIG_USER_802_1X
#undef  CONFIG_USER_WSC
#define CONFIG_USER_OPENSSL 1
#undef  CONFIG_USER_WPA_SUPPLICANT

/*
 * Wireless-tools
 */
#define CONFIG_USER_WIRELESS_TOOLS 1
#undef  CONFIG_USER_WIRELESS_IW_TOOL

/*
 * Miscellaneous Applications
 */
#define CONFIG_USER_BUSYBOX_BUSYBOX 1
#define CONFIG_USER_ETHTOOL 1
#define CONFIG_USER_NTFS3G 1
#undef  CONFIG_USER_NTFSPROGS
#define CONFIG_LIB_LIBNTFS3G_FORCE 1
#define CONFIG_LIB_LIBPTHREAD_FORCE 1
#undef  CONFIG_USER_STRACE_STRACE
#define CONFIG_USER_TCPDUMP 1
#undef  CONFIG_USER_CHILLISPOT
#define CONFIG_USER_E2FSPROGS 1
#define CONFIG_USER_MINIDLNA 1

/*
 * Ralink RT288x Application
 */
#define CONFIG_RT2880_APP 1
#undef  CONFIG_RT2880_REG_RW
#define CONFIG_RT2880_MII_MGR 1
#define CONFIG_RT2880_NVRAM 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#define CONFIG_RT2880_RAINIT 1
#define CONFIG_RT2880_MTD 1
#define CONFIG_ETHMAC_TOOL 1
#define CONFIG_RT2880_GPIO_TEST 1
#define CONFIG_RALINKAPP_HWNAT 1
#undef  CONFIG_RALINKAPP_HWNAT_AC
#undef  CONFIG_RALINKAPP_HWNAT_ACL
#undef  CONFIG_RALINKAPP_HWNAT_MTR
#define CONFIG_USER_IPROUTE2 1
#define CONFIG_USER_IPROUTE2_IP 1
#define CONFIG_USER_IPROUTE2_TC 1
#define CONFIG_RT3052_SWITCH 1
#undef  CONFIG_RTL8367M_SWITCH
#define CONFIG_RALINKAPP_SWQOS 1

/*
 * 3G support
 */
#define CONFIG_USB_MODESWITCH 1
#define CONFIG_LIB_USB 1

/*
 * Optimization options.
 */
#undef  CONFIG_LIB_SMALLSIZE
#undef  CONFIG_USER_SMALLSIZE
#undef  CONFIG_LIB_SAVERAM
#undef  CONFIG_USER_SAVERAM
#define CONFIG_VENDOR "Ralink"
#define CONFIG_PRODUCT "RT3052"
#define CONFIG_LINUXDIR "linux"
#define CONFIG_LIBCDIR ""
#define CONFIG_LANGUAGE "ru_UA:ru"
#define VENDORS_AUTOCONF_INCLUDED
#undef AUTOCONF_INCLUDED
